# Generated by Django 3.2.12 on 2024-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'primero'), (2, 'segundo'), (3, 'tercero'), (4, 'cuarto')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ciencias Sociales'), (2, 'Ciencias Exactas'), (3, 'Complementarios')], default=1),
            preserve_default=False,
        ),
    ]
